### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by rshin** [allenai/break-evaluator#3]
Could you add a license to the repository?

[GitHub's help page](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license) states:
> without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. 

https://choosealicense.com/no-permission/ states:
> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software.

Thanks!

**Comment by tomerwolgithub** [comment]
Sure thing!
